services:

  # OHDSI API
  ohdsi-api:
    image: harbor2.vantage6.ai/infrastructure/ohdsi-api:dev
    ports:
      - 5000:8000
    container_name: ohdsi-api
    restart: unless-stopped
    env_file:
      - .connection-details.env
    command: ["gunicorn", "-b", "0.0.0.0", "-w", "1", "api:app"]

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    container_name: rabbitmq

  # PostgreSQL for celery
  db:
    image: postgres:9.6
    ports:
      - 5454:5432
    container_name: postgres
    env_file:
      - .connection-details.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  celery-worker:
    image: harbor2.vantage6.ai/infrastructure/ohdsi-api:dev
    container_name: celery-worker
    command: celery -A api.celery_app worker -l DEBUG -P solo
    restart: unless-stopped
    env_file:
      - .connection-details.env
    depends_on:
      - rabbitmq
      - db


