name: CI

on:
    push:
        tags:
            - 'version/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Extract version
      run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/version/})" >> $GITHUB_ENV

    - uses: actions/checkout@v3

    - name: Set version
      run: make set-version VERSION=$VERSION

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: harbor2.vantage6.ai
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Run make image
      run: |
        make image
        make image TAG=$VERSION

    - name: Run make push
      run: |
        make push
        make push TAG=$VERSION